apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-ljom
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - env:
        - name: var_name
          value: test
        image: quay.io/redhat-appstudio-qe/release-e2e-deploy-tenant/appstudio/dc-metro-map-ljom@sha256:ca8e93b4753a61a787275d9f34153b72c2978987a9ae99ee9fbbbfa9f2d760b0
        name: my-nodejs
        resources: {}
status: {}
